#!/bin/bash -x

pip3 list --outdated | tail +3 | awk '{print $1}' | xargs pip3 install --upgrade

brew upgrade
brew cask upgrade

npm update

nvim +PlugUpdate +UpdateRemotePlugins +qall

stack upgrade

sudo tlmgr update --all
